spring:
  application:
    name: java.mid

  datasource:
    url: jdbc:h2:mem:java_mid_db
    driver-class-name: org.h2.Driver
    username: user
    password: pw

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

  cache:
    type: caffeine
    cache-names:
      - productsList
      - productById
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=10m
app:
  jwt:
    secret: "b7F!x9Q2#zL4@pR8$wT6^sV0*eN1%uK5&yM3"
    issuer: "abysaltO"
    access-token-ttl-minutes: 60
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha